# Generated by Django 4.1.2 on 2022-10-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='youtuber',
            name='tags',
            field=models.ManyToManyField(to='bloggers.tag', verbose_name='Tags'),
        ),
    ]
