# Generated by Django 4.1.2 on 2022-10-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0002_tag_youtuber_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twich_url', models.URLField(unique=True, verbose_name='Twich Link')),
                ('thumb_url', models.URLField(blank=True, null=True, verbose_name='Logo link')),
                ('subscribers', models.CharField(blank=True, max_length=20, null=True, verbose_name='Subscribers')),
                ('average_online', models.CharField(blank=True, max_length=20, null=True, verbose_name='Average online')),
                ('last_stream', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last stream')),
                ('tags', models.ManyToManyField(to='bloggers.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagram',
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(unique=True, verbose_name='Instagram Link')),
                ('thumb_url', models.URLField(blank=True, null=True, verbose_name='Logo link')),
                ('subscribers', models.CharField(blank=True, max_length=20, null=True, verbose_name='Subscribers')),
                ('involvement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Involvement')),
                ('tags', models.ManyToManyField(to='bloggers.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagram',
            },
        ),
    ]
