# Generated by Django 4.1.2 on 2022-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0003_twich_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='twich',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
    ]
