# Generated by Django 4.1.2 on 2022-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0004_instagram_title_twich_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twich',
            options={'verbose_name': 'Twich', 'verbose_name_plural': 'Twich'},
        ),
        migrations.RemoveField(
            model_name='instagram',
            name='thumb_url',
        ),
        migrations.AddField(
            model_name='instagram',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Logo link'),
        ),
    ]
