# Generated by Django 4.1.2 on 2022-10-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='area',
            field=models.CharField(max_length=10, verbose_name='Coverage'),
        ),
        migrations.AlterField(
            model_name='case',
            name='budget',
            field=models.CharField(max_length=10, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='case',
            name='geo',
            field=models.CharField(max_length=20, verbose_name='Geo'),
        ),
        migrations.AlterField(
            model_name='case',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='case',
            name='service',
            field=models.TextField(max_length=200, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
