# Generated by Django 4.1.2 on 2022-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_case_area_remove_case_budget_remove_case_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='color_theme',
            field=models.CharField(choices=[('yellow', 'yellow'), ('blue', 'blue'), ('mint', 'mint'), ('red', 'red'), ('ligth-blue', 'ligth-blue'), ('orange', 'orange'), ('pink', 'pink'), ('light', 'light'), ('green', 'green')], default='yellow', max_length=20, verbose_name='Color theme'),
        ),
    ]
