# Generated by Django 4.1.2 on 2022-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.CharField(choices=[('yellow', 'yellow'), ('blue', 'blue'), ('mint', 'mint'), ('red', 'red'), ('ligth-blue', 'ligth-blue'), ('orange', 'orange'), ('pink', 'pink'), ('light', 'light'), ('green', 'green')], default='yellow', max_length=20, verbose_name='Color theme')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('img', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('influencers', models.PositiveIntegerField(verbose_name='Influencers')),
                ('views', models.CharField(max_length=20, verbose_name='Views')),
                ('footer_text', models.TextField(blank=True, max_length='Footer text', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ('-created',),
            },
        ),
    ]
