# Generated by Django 4.1.2 on 2022-10-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color_theme',
            field=models.CharField(choices=[('yellow', 'yellow'), ('blue', 'blue'), ('mint', 'mint'), ('red', 'red'), ('ligth-blue', 'ligth-blue'), ('orange', 'orange'), ('pink', 'pink'), ('light', 'light'), ('green', 'green')], max_length=20, verbose_name='Color theme'),
        ),
    ]
