# Generated by Django 4.1.2 on 2022-10-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_project_color_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='case',
            name='footer_text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Footer text'),
        ),
        migrations.AlterField(
            model_name='case',
            name='influencers',
            field=models.CharField(max_length=20, verbose_name='Influencers'),
        ),
    ]
