# Generated by Django 4.1.2 on 2022-11-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_remove_case_description_remove_case_footer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='color_theme',
            field=models.CharField(choices=[('yellow', 'yellow'), ('blue', 'blue'), ('mint', 'mint'), ('red', 'red'), ('light-blue', 'light-blue'), ('orange', 'orange'), ('pink', 'pink'), ('light', 'light'), ('green', 'green')], default='yellow', max_length=20, verbose_name='Color theme'),
        ),
    ]
