# Generated by Django 4.1.2 on 2022-11-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_color_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('created',), 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
    ]
