# Generated by Django 4.1.2 on 2022-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_created_alter_partner_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.FileField(upload_to='images/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
