# Generated by Django 4.1.2 on 2022-10-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_fullname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post'),
        ),
    ]
