# Generated by Django 4.1.2 on 2022-10-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_author_fullname_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
