# Generated by Django 4.1.2 on 2022-10-23 14:35

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_content_remove_post_excerpt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ua',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt_ua',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ua',
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('excerpt', models.TextField(max_length=150, verbose_name='Short Excerpt')),
                ('content', models.TextField(verbose_name='Content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.post')),
            ],
            options={
                'verbose_name': 'New Translation',
                'db_table': 'blog_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
